version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - healthcare-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - healthcare-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - healthcare-net
    depends_on:
      redis:
        condition: service_healthy

  app:
    build: ../healthcare-backend
    container_name: spring_boot_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/healthcare_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
    networks:
      - healthcare-net

  frontend:
    build: ../healthcare-frontend
    container_name: react_frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - healthcare-net

volumes:
  db_data:
  redis_data:
  redis_insight_data:

networks:
  healthcare-net:
    driver: bridge